# Generated by Django 4.1 on 2022-10-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vehicle_no', models.IntegerField()),
                ('license_no', models.IntegerField()),
                ('aadhar_no', models.IntegerField()),
                ('model', models.CharField(max_length=20)),
            ],
        ),
    ]
