# Generated by Django 4.1 on 2022-10-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='savedata',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
